# Generated by Django 5.1.5 on 2025-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='event_type',
            field=models.CharField(choices=[('admin', 'Admin Assigned'), ('student', 'Student Created')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='studysession',
            name='requires_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
