# Generated by Django 5.1.5 on 2025-02-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_reply_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reply_files/'),
        ),
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reply_images/'),
        ),
    ]
