# Generated by Django 5.1.5 on 2025-02-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_reply_file_reply_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post_files/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
