# Generated by Django 5.1.6 on 2025-03-06 15:05

import myCWK.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_post_file_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post_files/', validators=[myCWK.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[myCWK.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='reply',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reply_files/', validators=[myCWK.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reply_images/', validators=[myCWK.validators.validate_file_extension]),
        ),
    ]
